### PR TITLE
Fix bug indexOf for IE8

### PR DESCRIPTION
**Pull request by apoutchika**
Change native indexOf function to underscore indexOf function.

### CODE REVIEW

**Comment by sarink** [comment]
Would you mind fixing the coffee, and recompiling the JS + sourcemap?

**Comment by apoutchika** [comment]
I discover the coffee-script, I think it's ok after a commit ...

**Comment by sarink** [comment]
I think you'll have to rebase your commit with master, and recompile.

**Comment by apoutchika** [comment]
I have merged you'r master branch, compiled and pushed. I'ts good?

**Comment by sarink** [comment]
Sorry this took me so long. Thanks for the fix.

**Pull request merged**
